### ISSUE TITLE
Implementation tracking

### ISSUE THREAD

**Issue by roj1512** [roj1512/wbb#2]
- [ ] Admin
	- [ ] Ban
		- [ ] /ban (user) (duration) (reason)
		- [ ] /dban (user) (duration) (reason)
		- [ ] /unban
		- [ ] -/tban: merged with /ban
	- [ ] Mute
		- [ ] /mute (use) (duration) (reason)
		- [ ] +/dmute (use) (duration) (reason)
		- [ ] /unmute
		- [ ] -/tban: merged with /mute
